### ISSUE TITLE
Email BODY html attachements weirdly formatted

### ISSUE THREAD

**Issue by JayTurnr** [django-helpdesk/django-helpdesk#719] opened 2019-02-07 15:51 UTC
Here's an example with sensitive information removed:

```
Please s= ee the confirmation email (about my Dec survey) as below.=C2=A0

---------------------

Hello,

This is a courtesy e-mail to let you know that t= icket [bugs-133] ("Missing survey: NHpokemon8") for=C2=SENSITIVE INFORMATION= =C2=A0has been updated.

Ticket ID: [bugs-133]
Queue: Bugs
Title: Missi= ng survey: SENSITIVE INFORMATION
Opened: Saturday Feb. 2nd 2019, at 6:39 p.m= .
Submitter:=C2=A0SENSITIVE INFORMATION
Priority: 2. High
Statu= s: Reopened
Assigned to:=C2=A0
View Online=C2=A0to upd= ate this ticket (login required)

Just for reference, the original ticket description was:

I submitted my Dec 2= 018 survey 11:54pm right before midnight, and I received email confirmation= immediately. But my data wasn=E2=80=99t in for that month. Now I am prompt= ed for =E2=80=9Cimporting undefined surveys=E2=80=9D. However nothin happen= ed after I click that button again and again.
```
Is there any reason this might be happening? 

Also, a few images are being saved as octlet-streams

**Comment by gwasser** [comment] 2019-02-08 07:59
For some reason the email's encoding is not being properly converted. Is this an email generated by `django-helpdesk`? Which version are you using? (current 0.2.x release or develop branch?)

**Comment by JayTurnr** [comment] 2019-02-08 13:43
This happens to all emails that gets pulled in via `get_email`, even plaintext email. I'm on version 0.2.13 😊

**Comment by gwasser** [comment] 2019-02-09 07:29
It's something to do with UTF encoding, I suppose it is getting encoded to ascii (maybe base64'd?). I think I might know the line that's doing it. I wonder if anyone else is running into this, and why the unit tests aren't catching it.

**Comment by johanovic** [comment] 2019-02-11 19:52
I get these errors quite regularly as well.

**Comment by gwasser** [comment] 2019-02-12 06:18
Hmm we should definitely look into this. Can anyone provide a simple email that recreates the issue?

**Comment by timthelion** [comment] 2019-03-06 12:02
This is caused by the fact that html email bodies are being encoded with the "Content-Transfer-Encoding" "quoted-printable" and helpdesk is not converting the files back to the "original" encoding of "utf-8". We need to be able to detect the transfer encoding and decode email parts.

https://stackoverflow.com/questions/14249288/change-quoted-printable-encoding-to-utf-8#14249341

**Comment by timthelion** [comment] 2019-03-06 12:52
If that fixes it, then the fix was pretty easy ;) just one argument needed to be added to get_payload...

**Comment by gwasser** [comment] 2019-03-06 16:28
Makes sense to me! I merged #729 for it but let me know if that didn't fix it.

**Comment by johanovic** [comment] 2019-09-08 19:05
Just a heads up to say that I am still having problems with emails that display the infamous `=` signs. This seems to be a consequence of quoted-printable encoding as @timthelion suggested above. His fix does not work for me though.

**Comment by timthelion** [comment] 2019-09-08 19:07
Please try to reproduce this minimally and add an eml file to the test suit. 

8. září 2019 21:06:04 SELČ, johanovic <notifications@github.com> napsal:

**Comment by johanovic** [comment] 2019-09-08 19:14
Well I am actually working with the test you provided `Tohle je test =C4=8Desk=C3=BDch p=C3=ADsmen odeslan=C3=BDch z gmailu.`

**Comment by gwasser** [comment] 2019-09-08 19:18
Thanks for the report @johanovic. Can you clarify, is an existing test not working properly? What can we do to fix it?

**Comment by johanovic** [comment] 2019-09-08 19:25
I cannot confirm whether the test is working, but in order to get the test email correctly parsed I need 

    last_payload
    (output:) '<div dir=3D"ltr">Tohle je test =C4=8Desk=C3=BDch p=C3=ADsmen odeslan=C3=BDc=\nh z gmailu.</div>\n'
    import quopri
    (output:) quopri.decodestring(last_payload)
    print(x.decode('utf8'))
    (output:)<div dir="ltr">Tohle je test českých písmen odeslaných z gmailu.</div>

**Comment by timthelion** [comment] 2019-09-08 19:42
Why can't you confirm it? Are you having trouble running the test suit?

8. září 2019 21:25:50 SELČ, johanovic <notifications@github.com> napsal:

**Comment by johanovic** [comment] 2019-09-08 20:02
Is there anything in the docs on how to run the test suite?

**Comment by timthelion** [comment] 2019-09-09 17:01
Any time you see a project using travis on github, you can find out how to run the test suit by looking at `.travis.yml`.

https://github.com/django-helpdesk/django-helpdesk/blob/master/.travis.yml#L21

In this case you need to run

    python3 quicktest.py helpdesk

**Closed** 2019-12-17 13:27 UTC
Labels: bug
