### ISSUE TITLE
<class 'ConnectionAbortedError'> - Não estou conseguindo pegar as paridades. Reinicie o bot: line 188 -> line 439

### ISSUE THREAD

**Issue by GuilhermeTerra** [django-helpdesk/django-helpdesk#977] opened 2021-09-29 02:18 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GuilhermeTerra** [comment] 2021-09-29 02:20
estou com esse problemas e outros comprei um bot para pegar sinais de OB e ele fica dando esses erros e alem disso da um erro de api nao entendo nada espero que me ajudem

**Comment by gwasser** [comment] 2021-09-29 20:15
Thank you, I'm guessing this is a duplicate of #621 ? This is a known problem on some Windows hosts. I will close this ticket as a duplicate, but please comment and follow on #621. I hope this is something folks can help fix as I'm not sure what to do.

**Closed by gwasser** 2021-09-29 20:15 UTC
Labels: bug
