### ISSUE TITLE
NoReverseMatch at /helpdesk/system_settings/

### ISSUE THREAD

**Issue by yugensoft** [django-helpdesk/django-helpdesk#569] opened 2017-11-19 11:39 UTC
I'm getting this error when trying to access the system settings
```
Request Method: | GET
-- | --
http://localhost:8000/helpdesk/system_settings/
Django Version: 1.11.4
Exception Type: NoReverseMatch
Exception Value: Reverse for 'main_user_changelist' not found. 'main_user_changelist' is not a valid view function or pattern name.
Exception Location: C:\Python27\lib\site-packages\django\urls\resolvers.py in _reverse_with_prefix, line 497

```

**Comment by gwasser** [comment] 2017-12-06 07:38
Hi there, what version of `django-helpdesk` are you using? Do you have any other django packages installed? I did a grep and couldn't find that function name anywhere in our code base, so I'm wondering if your django project is crossing the URLs between apps. Please check your django project configuration according to installation documentation.

**Comment by gwasser** [comment] 2017-12-09 17:15
Our demo (you can run it with `make rundemo2`) works fine with system settings on Py2/Django 1.11 for me. I can't reproduce this issue. Do you have any other info? Please take a look at the demo project configuration file to see if maybe you have an error in your project file.

**Comment by gwasser** [comment] 2017-12-16 02:54
I'm going to assume you were able to find the problem :-) I'm closing for now but feel free to reopen if you still have trouble.

**Closed by gwasser** 2017-12-16 02:54 UTC

**Comment by yugensoft** [comment] 2017-12-16 07:47
hi, I just didn't have enough time to try and debug this. I've taken down my helpdesk because it'd need too heavy customization to become usable for me (it seems more Jira-like than customer-help like), although all the basics seem to be in there. Might revisit it in the future.

**Comment by gwasser** [comment] 2017-12-18 01:09
Right now I think it is more JIRA like. What features do you think are missing for customer-help? There's ongoing work to allow more customization so please feel free to submit a PR for missing features or check out a future release.

**Comment by yugensoft** [comment] 2017-12-18 06:27
Cool, well I will need it (and there is no other viable django option), so when I come back to it I'll aim for some PRs.
Basically for public-facing customer help, the following options are needed:

1. Tickets should only be prioritizable (or due date change) and assignable by admins
1. The email address of the creator shouldn't be shown (privacy is important)
1. The yellow view tickets panel has css overlap issues on the text (doesn't bother a dev, but things like that hurt confidence from a customer)
1. The interface is unclear to a customer. I.e. dashboard only makes sense (assigned to you etc) in a JIRA-like context. They are more likely to click "Tickets", but that shows a search interface (but calls it "Query" which isn't as familiar to a customer). It would be better to have an option whereby (for "customer helpdesk mode"), they only see a "Tickets" tab, and that tab just shows a list of tickets, starting with their own. The search panel could be off to the side, or in a separate view, or a button + modal. At the moment it's taking up all of the page, so a customer has to scroll down to see tickets, something that is jarring to them (they expect just to see tickets when they click tickets).

Hope that info was useful, cheers
