### ISSUE TITLE
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by Isha307** [django-helpdesk/django-helpdesk#1008] opened 2022-04-03 08:04 UTC
I was trying to play an audio and got this error.
I tried [this](https://github.com/django-helpdesk/django-helpdesk/issues/621) but nothing helped.

Windows:: 10
python:: 3.7.7
Django:: 3.1.6

```
Exception happened during processing of request from ('127.0.0.1', 51084)
Traceback (most recent call last):
  File "c:\python\python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python\python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python\python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Isha\.virtualenvs\DJ-qI2Tt3md\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "C:\Users\Isha\.virtualenvs\DJ-qI2Tt3md\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\python\python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

**Comment by gwasser** [comment] 2022-07-02 10:19
Unfortunately this is a long known problem, see #621. Haven't quite figured out what's causing it, seems to be some issue with Django running on Windows. I will close this ticket since it is kind of a duplicate of #621.

**Closed by gwasser** 2022-07-02 10:19 UTC
Labels: bug
