### ISSUE TITLE
pip install django-helpdesk downgraded django

### ISSUE THREAD

**Issue by renelabounek** [django-helpdesk/django-helpdesk#819] opened 2020-05-02 06:15 UTC
When I executed pip install. It installed django-helpdesk, but it also downgraded django from version 3.0.5 at 2.2.12 or something like that without any asking me, if I want it or not.

I dislike this behaviour. 

Do you plan to update django-helpdesk for django 3.*?

**Comment by gwasser** [comment] 2020-05-02 15:57
Currently django-helpdesk only works with Django 2.2, it has a few errors when attempted to run in Django 3. I would like to support Django 3 but have not checked for compatibility yet. It's part of the next release milestone.

**Comment by renelabounek** [comment] 2020-05-03 05:47
That I understand there can be lots of work to update django-helpdesk for django 3.0.5. I was just surprised the pip downgraded my django without asking for my permission/approval.

**Comment by gwasser** [comment] 2020-05-03 06:50
That must be some unexpected behavior of pip. Our requirements.txt file includes the line `Django>=2.2.9,<3` which would force pip to install a Django 2.2.x to satisfy.

**Comment by renelabounek** [comment] 2020-05-04 18:29
Either ways, it forced to downgrade the django without asking.

**Comment by hellcheese** [comment] 2020-07-12 17:29
> Either ways, it forced to downgrade the django without asking.

I think this normal behavior of pip - happens to me with other modules and not just django-helpdesk

**Comment by gwasser** [comment] 2020-10-07 06:01
Yep @hellcheese  is right, that's just how pip behaves when you set requirements versions. `django-helpdesk` won't work with Django 3.x yet so it downgraded you to make all your packages work. It's not something to "fix" other than to add Django 3.x support to this project. #827 is a duplicate, I'll probably close this one since it's not really a problem with pip itself. There's a new effort for hacktober maybe to get our 0.3.x release finally finished up which would support django 3.x -- folks interested in contributing can check it out at #878.

**Closed by gwasser** 2020-10-07 06:01 UTC
Labels: bug

**Comment by achillis2** [comment] 2021-05-11 21:45
Thanks for the help. I was able to install the helpdesk. However when I tried to run migration or runserver, I got the error below. 

`RuntimeError: Model class account.models.Account doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

**Comment by Benbb96** [comment] 2021-05-11 21:51
Did you updated your `INSTALLED_APPS` accordingly to the docs here : https://github.com/django-helpdesk/django-helpdesk/blob/master/docs/install.rst ?

**Comment by gwasser** [comment] 2021-05-11 22:10
Oh sorry, it's settings.py! I was going off the top of my head and that was
a bad idea :-)

**Comment by gwasser** [comment] 2021-05-11 22:12
You can check the settings.py file under the demo/ folder in the repo and
compare with what you're using. If I recall correctly, you have to put them
in that order more or less, or some apps might not load correctly because
their dependencies weren't loaded yet.

**Comment by achillis2** [comment] 2021-05-11 22:17
Ok, it seems there is a conflicting between helpdesk required package and my own package.

**Comment by darshmodi97** [comment] 2021-06-15 06:16
I have installed django-allauth module which has its own account. I have installed this beta version of django-helpdesk==0.3.0b3 and now I am trying to add "account" in  **settings.py/installed apps** but I got the error 
**django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: account**
even I don't have my own account. It's all about 3rd party account app so can you help me how can I solve this damn error??

**Comment by timthelion** [comment] 2021-06-15 07:16
@darshmodi97 I think that this is caused by a conflict with pinax-teams. We need to finish https://github.com/django-helpdesk/django-helpdesk/pull/913

**Comment by timthelion** [comment] 2021-06-15 07:17
I just haven't had time to pull that one to the finish line...

**Comment by darshmodi97** [comment] 2021-06-15 07:19
@timthelion, thanks for replying and yeah there is a comment that says required by pinax-teams in settings.py/installed apps.
