### ISSUE TITLE
Dashboard,  open tickets assigned to you and Duplicate status

### ISSUE THREAD

**Issue by buoncri** [django-helpdesk/django-helpdesk#1205] opened 2024-09-12 09:08 UTC
**Describe the bug**
In "_Dashboard_" page, in frame " _Open Tickets assigned to you_", tickets with "_Duplicate_" status remain there still after they are solved through the main ticket, which is correctly moved to " _Closed & resolved Tickets you used to work on_" frame.

**To Reproduce**
1. Create ticket one
2. Create ticket two
3. Merge tickets and solve

**Expected behavior**
I think merged tickets with duplicate status can go on the same frame of the solved one ... or in a dedicated frame for duplicates, so on the " _Open Tickets assigned to you_", we can have really open tickets as default.

**Comment by buoncri** [comment] 2024-09-12 09:59
If someone with more knowledge of django-helpdesk can direct me to a possible solution, i will try a pr.

**Comment by jorge-leon** [comment] 2024-09-13 10:43
How to find the code for a view:

- Look at the url where the problem is.
- Find the url in the `urlpatterns` variable in the `url.py` file.
- Look up the class/method registered for the url.

In our case: url is `dashboard`, method is `staff.dashboard`, file is `views/staff.py`, method `dashboard` on line 125.

From there you should find your way around.

IMHO tickets marked as duplicate are immediately "solved". I'd go for this solution first.

**Comment by uhurusurfa** [comment] 2024-09-13 15:12
I agree with @jorge-leon 
Just to be clear, tickets identified as duplicate have their status set to duplicate so will not be closed.
The query to show active tickets should exclude tickets with a status set to duplicate in the [active tickets query](https://github.com/django-helpdesk/django-helpdesk/blob/6c8a6eaee16c9e5b666ab17055a6609b34e80490/helpdesk/views/staff.py#L145).

**Closed** 2024-09-17 06:08 UTC
Labels: bug
