### ISSUE TITLE
Bug with due date (not fix)

### ISSUE THREAD

**Issue by lbopp42** [django-helpdesk/django-helpdesk#624] opened 2018-07-16 13:55 UTC
Hello,
When I create a ticket without "Due on" and I edit this one, I got an error.
`

Request Method: | POST
-- | --
http://site.fr:8030/tickets/4/update/
2.0.7
ValidationError
["'' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format."]
/path/apps/helpdesk/lib/python3.5/site-packages/django/db/models/fields/__init__.py in to_python, line 1395
/path/apps/helpdesk/bin/python
3.5.2
['/path/apps/helpdesk/helpdesk_ticket',  '/path/apps/helpdesk/lib/python35.zip',  '/path/apps/helpdesk/lib/python3.5',  '/path/apps/helpdesk/lib/python3.5/plat-x86_64-linux-gnu',  '/path/apps/helpdesk/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/path/apps/helpdesk/lib/python3.5/site-packages']
Mon, 16 Jul 2018 13:44:06 +0000

`
I see this issue with a ticket dated of 2012. Since 2012 you don't fix it ?

Regards,
BOPP Lucas

**Comment by gwasser** [comment] 2018-07-17 19:13
Are you using the latest release (0.2.8)? I did just check in a fix that's in `master` and not yet released so please try that and let me know if it fixes the problem. Python 3 support is new and still working out some issues with it.

**Comment by gwasser** [comment] 2018-07-17 21:48
Awesome! Thanks for the feedback. Since this is an important fix and now  confirmed, I'll roll it into a 0.2.9 bugfix release ASAP.

**Comment by gwasser** [comment] 2018-07-19 02:44
This should be fixed now in the 0.2.9 release, please let me know if there's any problems! Thanks for confirming.

**Closed by gwasser** 2018-07-19 02:44 UTC
Labels: bug

**Comment by lbopp42** [comment] 2018-07-19 08:11
Hello,
This seems to be fixed thanks :+1:

**Comment by tboulogne** [comment] 2018-11-01 08:42
Hello,

I'm running django-helpdesk 0.2.10 and i face this error.
Workarroun this by overring datepicker initilisation to :
``
$("#id_due_date").datepicker({
                format: "yyyy-mm-dd",
                language: 'fr'
            });
``
and make some JS.

It could be nice to see this solved a python way ;-)

Thanks :-).
