### ISSUE TITLE
get_email crashes when fetching a signed email

### ISSUE THREAD

**Issue by monkeypants** [django-helpdesk/django-helpdesk#567] opened 2017-11-04 13:29 UTC
if someone sends my helpdesk an email with a GPG signature attached (signed, not enctypted, detached sig not inline, using enigmail plugin for thunderbird), then `manage.py get_email` crashes like this:
```
 ./manage.sh get_email
***** Sat Nov  4 13:25:02 2017: Begin processing mail for django-helpdesk
Attempting IMAP server login
Received 1 messages from IMAP server
Processing message b'1'
No tracking ID matched.
Traceback (most recent call last):
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/base64.py", line 517, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chtis/src/monkeypants/goodies-taskdesk/src/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 73, in handle
    process_email(quiet=quiet)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 106, in process_email
    process_queue(q, logger=logger)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 209, in process_queue
    ticket = ticket_from_message(message=full_message, queue=q, logger=logger)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/site-packages/helpdesk/management/commands/get_email.py", line 348, in ticket_from_message
    payloadToWrite = base64.decodestring(payload)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/base64.py", line 561, in decodestring
    return decodebytes(s)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/home/chtis/src/monkeypants/goodies-taskdesk/.venv/lib/python3.6/base64.py", line 520, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```

It's entirely possible I have a stupid config problem with my site, it's a new project and I'm just starting out with django-helpdesk.

**Comment by gwasser** [comment] 2017-11-07 04:48
We recently added Python 3 support and so there's been a few kinks here in there. Looks like we have a `bytes` and `str` mismatch here, so that's a bug in our Py 3 code. Thanks for the report! I'll take a look at how to fix this.

**Comment by monkeypants** [comment] 2017-11-07 07:57
Let me know if you want me to send a "toxic" (make crash for me) email somewhere.

**Comment by gwasser** [comment] 2017-11-07 14:57
If you'd like to paste a sample email into a comment, that might be helpful (make sure it has no personal info). Thanks!

**Comment by monkeypants** [comment] 2017-11-08 06:01
It's not a matter of email body, it's the whole thing (MIME endoded sig). I could try base64 encoding it then pasting that junk to a gist... but easier to reproduce if I just send it to a convenient inbox.

**Comment by gwasser** [comment] 2017-11-08 20:25
MIME encoded signatures in the body or as an attachment? If it's easily reproducible, I can create a mail on my end to test with. As `get_email` was being updated I started adding test cases and obviously haven't created test emails for everything yet :-)

**Comment by monkeypants** [comment] 2017-11-08 20:43
I'm note sure. To reproduce, I use thunderbird (with enigmail plugin) to send a signed (but not encrypted) email to my queue.

**Comment by gwasser** [comment] 2017-11-08 20:47
Just in case there's some oddness, you can send that email to <garret@wassiverse.com> and I'll take a look. Thanks!

**Comment by gwasser** [comment] 2017-11-08 20:48
It turns out email is a very hard problem and almost every client does something slightly different with its headers or formatting. It's pretty annoying.

**Comment by monkeypants** [comment] 2017-11-12 03:55
Hacking this into line ~346 of get_email.py works for me in python 3.6, not sure about the other versions you support though. It's a bit of a guess :)
```
            # base64 error signatures changed in python3                                                
            if sys.version_info()[0] < 3:
		non_b64_err = binascii.Error
            else:
                non_b64_err = TypeError
	    try:
                logger.debug("Try to base64 decode the attachment payload")
                payloadToWrite = base64.decodestring(payload)
            except non_b64_err:
                logger.debug("Payload was not base64 encoded, using raw bytes")
                payloadToWrite = payload
```

**Comment by gwasser** [comment] 2017-12-05 08:59
OK I believe this issue was fixed on `master`, I updated the test cases to ensure the test email you sent me works. If you have a moment please check out `master` and ensure you don't get any problems. I'll roll this into a bugfix release shortly. I'm closing for now but please reopen or file new ticket if you find any other problems. Thanks for your help!

**Closed by gwasser** 2017-12-05 08:59 UTC
Labels: bug

**Comment by monkeypants** [comment] 2017-12-05 10:47
Seems fixed to me, thanks!
