### ISSUE TITLE
Failed to install demo using both 'make rundemo' and docker variants

### ISSUE THREAD

**Issue by Tur8008** [django-helpdesk/django-helpdesk#1163] opened 2024-02-22 15:10 UTC
**Describe the bug**
Once make command had done its job it throws the exception `ModuleNotFoundError` see screenshort 

**To Reproduce**
1. Download help-desk-package from github
2.  Extract the data into folder then go to it
3.  Execute `make rundemo` command  from CLI 

If I use docker variant I get the same error. It seems like it has lack of dependecies named demo.
By the way.
If use the command `docker build . -t demodesk docker run --rm -v "$PWD:/app" -p 8080:8080 demodesk` from the docs it doesn't work because of error
![image](https://github.com/django-helpdesk/django-helpdesk/assets/9642686/dfb7caa9-649b-4a76-bdee-12f3c52feb93)

**Desktop (please complete the following information):**
 -  Ubuntu 20.04 LTS via WSL2 of Windows 11

![image](https://github.com/django-helpdesk/django-helpdesk/assets/9642686/84e47e4a-e6be-433c-a290-6b8ad47b1f2a)

**Comment by attieretief** [comment] 2024-03-11 10:01
Similar issue experience on Macos, latest package, running in virtualevn

**Comment by Benbb96** [comment] 2024-03-11 14:24
I can confirm I face same error on Linux, after git cloning the project, creating virtualenv and run `make rundemo`.

After investigating, I found the problem is coming from a change I made 3 years ago : https://github.com/django-helpdesk/django-helpdesk/commit/c2276ce7e16c2d90f99ba797dd1b93ec66b96f99

I believe it's because I was running the demo server with Pycharm integrated config tasks so the path was not resolving.  
I suggest reverting this commit to fix the problem.

As for the Docker variant, it supposed to be two distinct commands but there is an error in `README.rst` which displays it on one line. I'm going to fix it with the revert.

**Closed** 2024-03-17 15:14 UTC
Labels: bug
