### ISSUE TITLE
ValueError: I/O operation on closed file 

### ISSUE THREAD

**Issue by mrkiwi-nz** [django-helpdesk/django-helpdesk#413] opened 2016-07-04 03:38 UTC
When attaching a file to a ticket the following error occurs
ValueError: I/O operation on closed file
`[04/Jul/2016 15:01:08] ERROR [django.request:255] Internal Server Error: /helpdesk/tickets/21/update/
Traceback (most recent call last):
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/middleware/exception.py", line 35, in __call__
    response = self.get_response(request)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 277, in _legacy_get_response
    response = self._get_response(request)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 194, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 192, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/helpdesk/views/staff.py", line 553, in update_ticket
    files=files,
  File "/home/e-smith/files/ibays/django/django_app/m10_repo/m10virtualenv/lib/python2.7/site-packages/helpdesk/lib.py", line 143, in send_templated_mail
    msg.attach(filename=attachment[0], content=file_to_attach.read())
ValueError: I/O operation on closed file
`

**Comment by rossp** [comment] 2016-07-04 22:48
@mrkiwi-nz do you have any information about what triggered this? does the file exist (ie has it been saved to the filesystem), what file storage backend are you using, etc?

**Comment by mrkiwi-nz** [comment] 2016-07-04 22:59
The file is saved to the file system and the ticket status/attachment is all saved and ok, as proved by viewing the ticket in another window and being able to download the attachment. 
I think this bug triggers when the email system tries to pickup the file and attach to the email? I didn't have time to replicate on my localhost, attach the debugger and step through, but i will do later in the week - crazy workload right now. I am using an ldap backend for auth, but other than that it's a standard install (django 1.10a1, mysql). More debug later, D

**Comment by mrkiwi-nz** [comment] 2016-11-08 02:15
This issue happened again - adding an attachment at the time of creating a ticket caused 
the following error ( from httpd/error.log )

`[Tue Nov 08 14:48:40 2016] [error] [08/Nov/2016 14:48:40] ERROR [django.request:255] Internal Server Error: /helpdesk/tickets/submit/
[Tue Nov 08 14:48:40 2016] [error] Traceback (most recent call last):
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/middleware/exception.py", line 35, in __call__
[Tue Nov 08 14:48:40 2016] [error]     response = self.get_response(request)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 277, in _legacy_get_response
[Tue Nov 08 14:48:40 2016] [error]     response = self._get_response(request)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 194, in _get_response
[Tue Nov 08 14:48:40 2016] [error]     response = self.process_exception_by_middleware(e, request)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 192, in _get_response
[Tue Nov 08 14:48:40 2016] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
[Tue Nov 08 14:48:40 2016] [error]     return view_func(request, *args, **kwargs)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/helpdesk/views/staff.py", line 943, in create_ticket
[Tue Nov 08 14:48:40 2016] [error]     ticket = form.save(user=request.user)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/helpdesk/forms.py", line 300, in save
[Tue Nov 08 14:48:40 2016] [error]     files=files,
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/helpdesk/lib.py", line 143, in send_templated_mail
[Tue Nov 08 14:48:40 2016] [error]     msg.attach(filename=attachment[0], content=file_to_attach.read())
[Tue Nov 08 14:48:40 2016] [error] ValueError: I/O operation on closed file
[Tue Nov 08 14:48:40 2016] [error] [08/Nov/2016 14:48:40] ERROR [django.request:255] Internal Server Error: /helpdesk/tickets/submit/
[Tue Nov 08 14:48:40 2016] [error] Traceback (most recent call last):
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/middleware/exception.py", line 35, in __call__
[Tue Nov 08 14:48:40 2016] [error]     response = self.get_response(request)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 277, in _legacy_get_response
[Tue Nov 08 14:48:40 2016] [error]     response = self._get_response(request)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 194, in _get_response
[Tue Nov 08 14:48:40 2016] [error]     response = self.process_exception_by_middleware(e, request)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 192, in _get_response
[Tue Nov 08 14:48:40 2016] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
[Tue Nov 08 14:48:40 2016] [error]     return view_func(request, *args, **kwargs)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/helpdesk/views/staff.py", line 943, in create_ticket
[Tue Nov 08 14:48:40 2016] [error]     ticket = form.save(user=request.user)
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/helpdesk/forms.py", line 300, in save
[Tue Nov 08 14:48:40 2016] [error]     files=files,
[Tue Nov 08 14:48:40 2016] [error]   File "/home/e-smith/files/ibays/django/django_app/customer_repo/customervirtualenv/lib/python2.7/site-packages/helpdesk/lib.py", line 143, in send_templated_mail
[Tue Nov 08 14:48:40 2016] [error]     msg.attach(filename=attachment[0], content=file_to_attach.read())
[Tue Nov 08 14:48:40 2016] [error] ValueError: I/O operation on closed file
`

**Comment by mrkiwi-nz** [comment] 2016-11-08 03:23
However .... once the ticket is created, the attachment can be added as a followup via the interface, or the admin, so this points to the perms on the upload dir being ok (otherwise it should fail in all interfaces and all modes)
I suspect that its the codepath here ...

lib.py - line 142

The first time that send_templated_mail is hit, the file is opened properly, and closed properly, however `file_to_attach._file` is left populated.
The 2nd time send_templated_mail is hit (eg when another email is sent such as when there is a CC set in the config) the `file_to_attach.open()` call (line 142) passes silently, but if you call `file_to_attach.closed` immediately after this, you'll see that the file is actually closed. Therefore it is logical that the next line ( which contains `file_to_attach.read()` ) fails.

**Comment by mrkiwi-nz** [comment] 2016-11-08 03:26
I think the reason that this occurs at ticket creation and not at update is that ticket updating (in my case) sends 1 email where as ticket creation sends 2 ( a "to" and a "cc" )

Adding this fixes the problem for me;

`lib.py, line 145

file_to_attach._file = None
`

**Comment by reduxionist** [comment] 2016-11-08 04:35
Thanks for the updated report and for tracking down the cause and even a probable fix for us too! Since I don't want to submit a patch for this without also including a test case for it, I personally won't be able to issue a fix until this weekend. Apologies for the inconvenience!

**Comment by mrkiwi-nz** [comment] 2016-11-09 22:16
I can write a test if you want - just not sure how to mock or post the attached file, any hints or sample code would be appreciated.

**Comment by flinz** [comment] 2016-11-09 22:18
Look for mock_open, you can specify what a mocked file contains and it should also emulate opening and closing.

**Comment by gwasser** [comment] 2016-11-11 07:41
@mrkiwi-nz thanks for working on a test! Take a look at the tests for the get_email.py for inspiration, it uses mock to mock the contents of a file for reading. (see https://github.com/django-helpdesk/django-helpdesk/blob/master/helpdesk/tests/test_get_email.py)

**Comment by reduxionist** [comment] 2016-12-11 00:03
This test was trickier than it sounded because it can trip over [Python issue 21258](http://bugs.python.org/issue21258), the patch for which has been waiting for release for almost two years now. We have merged a fix for this in PR #463 just now, so please let us know if you still encounter any problems with this issue. In the meantime, however, I'm marking this ticket closed - thanks for your help getting it worked out! 😄

**Closed by reduxionist** 2016-12-11 00:03 UTC
Labels: bug
